'use client'

import React, { createContext, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'pt'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

const translations = {
  en: {
    'app_name': 'Gamer Hub',
    'home': 'Home',
    'search': 'Search',
    'bookings': 'Bookings',
    'games': 'Games',
    'achievements': 'Achievements',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',
    'athlete_stats': 'Athlete Stats',
    'level': 'Level',
    'facilities_visited': 'Facilities Visited',
    'friends': 'Friends',
    'search_facilities': 'Search sports facilities...',
    'featured_facility': 'Featured Facility',
    'book_now': 'Book Now',
    'wallet': 'Wallet',
    'booking_history': 'Booking History',
    'user_name': 'John Athlete',
    'user_email': 'john@example.com',
    'help_support': 'Help & Support',
    'invite_friend': 'Invite a Friend',
    'invite_friend_description': 'Invite your friends to join the game!',
    'friend_email': "Friend's email",
    'send_invite': 'Send Invite',
    'your_friends': 'Your Friends',
    'challenge': 'Challenge',
    'language': 'Language',
    'choose_language': 'Choose your preferred language',
    'social_media_links': 'Social Media Links',
    'link_social_media': 'Link your social media accounts to share achievements',
    'save_settings': 'Save Settings',
    'book_facility': 'Book {name}',
    'select_date_time': 'Select the date and time for your booking',
    'time': 'Time',
    'confirm_booking': 'Confirm Booking',
    'login': 'Login',
    'start': 'Start',
    'access_gaming_hub': 'Access your gaming hub',
    'email': 'Email',
    'password': 'Password',
    'enter': 'Enter',
    'continue_with': 'Or continue with',
    'no_account': 'Don\'t have an account?',
    'create_account': 'Create account',
    'player_registration': 'Player Registration',
    'new_game': 'New Game',
    'create_player_profile': 'Create your player profile to join the game',
    'player_name': 'Player Name',
    'confirm_password': 'Confirm Password',
    'contact_number': 'Contact Number',
    'birth_date': 'Birth Date',
    'select_class': 'Select Class',
    'warrior': 'Warrior',
    'mage': 'Mage',
    'rogue': 'Rogue',
    'mystery': 'Mystery',
    'id_number': 'ID Number',
    'continue_quest': 'Continue Quest',
    'already_have_account': 'Already have an account?',
    'login_continue_journey': 'Login to continue your journey',
    'base_location': 'Base Location',
    'checkpoint': 'Checkpoint',
    'set_spawn_point': 'Set your spawn point coordinates',
    'street': 'Street',
    'number': 'Number',
    'reviews': 'Reviews',
    'complement': 'Complement',
    'district': 'District',
    'city': 'City',
    'state': 'State',
    'accept_terms': 'I accept the terms of service and game rules',
    'complete_registration': 'Complete Registration',
    'link_account': 'Link Account',
    'payment_methods': 'Payment Methods',
    'add_payment_method': 'Add Payment Method',
    'current_balance': 'Current Balance',
    'transaction_history': 'Transaction History',
    'welcome_to_app': 'Welcome to Gamer Hub',
    'onboarding_welcome_message': 'Let\'s get you started with our app!',
    'key_features': 'Key Features',
    'feature_1': 'Book sports facilities easily',
    'feature_2': 'Manage your bookings',
    'feature_3': 'Track your progress and achievements',
    'how_to_book': 'How to Book',
    'booking_instructions': 'Browse facilities, select a date and time, and confirm your booking.',
    'payment_instructions': 'Add your preferred payment methods for quick and easy transactions.',
    'app_settings': 'App Settings',
    'choose_theme': 'Choose Theme',
    'light': 'Light',
    'dark': 'Dark',
    'previous': 'Previous',
    'next': 'Next',
    'finish': 'Finish',
    'upcoming': 'Upcoming',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'booking_details': 'Booking Details',
    'minutes': 'minutes',
    'price': 'Price',
    'status': 'Status',
    'card_holder': 'Card Holder',
    'add_card': 'Add Card',
    'your_payment_methods': 'Your Payment Methods',
    'expires': 'Expires',
    'upcoming_games': 'Upcoming Games',
    'recent_activities': 'Recent Activities',
    'leaderboard': 'Leaderboard',
    'view_all': 'View All',
    'points': 'Points',
    'rank': 'Rank',
    'total_games': 'Total Games',
    'win_rate': 'Win Rate',
    'xp': 'XP',
    'xp_progress': 'XP Progress',
    'level_up': 'Level Up!',
    'new_level': 'You\'ve reached level {level}!',
    'xp_earned': 'You\'ve earned {xp} XP!',
    'first_blood': 'First Blood',
    'first_blood_desc': 'Make your first reservation',
    'regular_player': 'Regular Player',
    'regular_player_desc': 'Make 10 reservations',
    'facility_explorer': 'Facility Explorer',
    'facility_explorer_desc': 'Visit 5 different facilities',
    'social_butterfly': 'Social Butterfly',
    'social_butterfly_desc': 'Add 5 friends',
    'influencer': 'Influencer',
    'influencer_desc': 'Share your first achievement on social media',
    'early_bird': 'Early Bird',
    'early_bird_desc': 'Make a reservation before 8 AM',
    'night_owl': 'Night Owl',
    'night_owl_desc': 'Make a reservation after 10 PM',
    'streak_master': 'Streak Master',
    'streak_master_desc': 'Make reservations for 7 consecutive days',
    'diverse_athlete': 'Diverse Athlete',
    'diverse_athlete_desc': 'Try 3 different types of sports',
    'referral_king': 'Referral King',
    'referral_king_desc': 'Refer 3 friends who make reservations',
    'match_registration': 'Match Registration',
    'match_list': 'Match List',
    'add_match': 'Add Match',
    'edit_match': 'Edit Match',
    'update_match': 'Update Match',
    'notes': 'Notes',
    'start_time': 'Start Time',
    'end_time': 'End Time',
    'select_field': 'Select Field',
    'field': 'Field',
    'add_comment': 'Add Comment',
    'enter_comment': 'Enter your comment here',
    'rate_facility': 'Rate Facility',
    'submit_comment': 'Submit Comment',
    'comment_added': 'Comment added successfully',
    'game_shared': 'Game shared successfully',
    'facility_details': 'Facility Details',
    'facility_description': 'Description',
    'facility_description_text': 'Modern sports facility with professional equipment and amenities.',
    'amenities': 'Amenities',
    'parking': 'Parking Available',
    'lockers': 'Lockers',
    'showers': 'Showers',
    'equipment_rental': 'Equipment Rental',
    'share_your_experience': 'Share your experience with this facility...',
    'submit_review': 'Submit Review',
    'review_submitted': 'Review Submitted',
    'thank_you_feedback': 'Thank you for your feedback!',
    'image': 'Image',
    'facility_image': 'Facility Image',
    'select_time': 'Select Time',
    'booking_success': 'Booking Successful',
    'booking_error': 'Booking Error',
    'please_select_date': 'Please select a date',
    'please_select_time': 'Please select start and end time',
    'please_select_field': 'Please select a field',
    'facility_images': 'Facility Images',
    'slide': 'Slide',
    'previous_image': 'Previous Image',
    'next_image': 'Next Image',
    'loading': 'Loading...',
    'no_bookings': 'No bookings found',
    'no_bookings_desc': 'You haven\'t made any bookings yet',
    'book_facility_now': 'Book a facility now',
    'booking_confirmation': 'Booking Confirmation',
    'booking_summary': 'Booking Summary',
    'selected_date': 'Selected Date',
    'selected_time': 'Selected Time',
    'selected_field': 'Selected Field',
    'total_price': 'Total Price',
    'payment_method': 'Payment Method',
    'confirm_and_pay': 'Confirm and Pay',
    'booking_rules': 'Booking Rules',
    'min_duration': 'Minimum duration: 1 hour',
    'max_duration': 'Maximum duration: 3 hours',
    'cancellation_policy': 'Free cancellation up to 24 hours before',
    'facility_rules': 'Facility Rules',
    'proper_attire': 'Proper sports attire required',
    'equipment': 'Equipment available for rent',
    'no_food': 'No food or drinks allowed',
    'arrive_early': 'Please arrive 10 minutes early',
    'mobile_menu': 'Mobile Menu',
    'close_menu': 'Close Menu',
    'view_profile': 'View Profile',
    'edit_profile': 'Edit Profile',
    'view_bookings': 'View Bookings',
    'my_bookings': 'My Bookings',
    'active_bookings': 'Active Bookings',
    'past_bookings': 'Past Bookings',
    'facility_location': 'Facility Location',
    'get_directions': 'Get Directions',
    'share_facility': 'Share Facility',
    'report_issue': 'Report Issue',
    'save_favorite': 'Save to Favorites',
    'remove_favorite': 'Remove from Favorites',
    'facility_saved': 'Facility saved to favorites',
    'facility_removed': 'Facility removed from favorites',
    'available_times': 'Available Times',
    'no_times_available': 'No times available for selected date',
    'try_another_date': 'Please try another date',
    'peak_hours': 'Peak Hours',
    'off_peak_hours': 'Off-Peak Hours',
    'peak_hour_rates': 'Peak Hour Rates Apply',
    'off_peak_rates': 'Off-Peak Rates Apply',
    'facility_reviews': 'Facility Reviews',
    'mock_review': 'This is a great facility! I enjoyed my time here and would definitely come back.',
    'write_review': 'Write a Review',
    'write_your_review': 'Write your review here...',
    'match_results': 'Match Results',
    'match_date': 'Match Date',
    'team': 'Team',
    'team_name': 'Team Name',
    'score': 'Score',
    'submit_results': 'Submit Results',
    'Personal': 'Personal',
    'Contact': 'Contact',
    'Security': 'Security',
    'full_name': 'Full Name',
    'phone_number': 'Phone Number',
    'id_document': 'ID Document',
    'end_session': 'End Session',
    'recent_achievements': 'Recent Achievements',
    'help_and_support': 'Help and Support',
    'search_faqs': 'Search FAQs',
    'search_faqs_description': 'Find answers to common questions',
    'search_placeholder': 'Type your question here...',
    'frequently_asked_questions': 'Frequently Asked Questions',
    'contact_support': 'Contact Support',
    'contact_support_description': 'Can\'t find what you\'re looking for? Send us a message.',
    'your_name': 'Your Name',
    'your_email': 'Your Email',
    'your_question': 'Your Question',
    'submit_question': 'Submit Question',
    'query_submitted': 'Query Submitted',
    'query_submitted_description': 'We\'ve received your question and will get back to you soon.',
    'faq_question_1': 'How do I book a facility?',
    'faq_answer_1': 'To book a facility, navigate to the home page, select the desired facility, choose an available time slot, and confirm your booking.',
    'faq_question_2': 'Can I cancel my booking?',
    'faq_answer_2': 'Yes, you can cancel your booking up to 24 hours before the scheduled time without any penalty.',
    'faq_question_3': 'How do I view my booking history?',
    'faq_answer_3': 'You can view your booking history by going to your profile and clicking on the "Booking History" button.',
    'faq_question_4': 'How do I update my profile information?',
    'faq_answer_4': 'To update your profile information, go to your profile page and click on the "Edit Profile" button. You can then modify your details in the respective tabs.',
    'faq_question_5': 'How do I earn XP and level up?',
    'faq_answer_5': 'You earn XP by booking facilities, completing games, and achieving various in-app milestones. As you accumulate XP, you\'ll automatically level up and unlock new features and rewards.',
    'match_info_registration': 'Match Information Registration',
    'match_info_description': 'Keep track of your matches and team performance.',
    'match_info_feature_1': 'Record match scores and statistics',
    'match_info_feature_2': 'Track individual player performance',
    'match_info_feature_3': 'Generate match reports and analytics',
    'facility_ratings': 'Facility Ratings',
    'ratings_description': 'Rate and review the facilities you visit.',
    'ratings_feature_1': 'Rate facilities based on various criteria',
    'ratings_feature_2': 'Read and write detailed reviews',
    'ratings_feature_3': 'Help other users find the best facilities',
    'more': 'More',
    'match_info': 'Match Info',
    'ratings': 'Ratings',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
  },
  pt: {
    'app_name': 'Central do Jogador',
    'home': 'Início',
    'search': 'Buscar',
    'bookings': 'Reservas',
    'games': 'Jogos',
    'achievements': 'Conquistas',
    'settings': 'Configurações',
    'profile': 'Perfil',
    'logout': 'Sair',
    'athlete_stats': 'Estatísticas do Atleta',
    'level': 'Nível',
    'facilities_visited': 'Instalações Visitadas',
    'friends': 'Amigos',
    'search_facilities': 'Buscar instalações esportivas...',
    'featured_facility': 'Instalação em Destaque',
    'book_now': 'Reservar Agora',
    'wallet': 'Carteira',
    'booking_history': 'Histórico de Reservas',
    'user_name': 'João Atleta',
    'user_email': 'joao@exemplo.com',
    'help_support': 'Ajuda e Suporte',
    'invite_friend': 'Convidar um Amigo',
    'invite_friend_description': 'Convide seus amigos para participar do jogo!',
    'friend_email': 'Email do amigo',
    'send_invite': 'Enviar Convite',
    'your_friends': 'Seus Amigos',
    'challenge': 'Desafiar',
    'language': 'Idioma',
    'choose_language': 'Escolha seu idioma preferido',
    'social_media_links': 'Links de Redes Sociais',
    'link_social_media': 'Vincule suas contas de redes sociais para compartilhar conquistas',
    'save_settings': 'Salvar Configurações',
    'book_facility': 'Reservar {name}',
    'select_date_time': 'Selecione a data e hora para sua reserva',
    'time': 'Hora',
    'confirm_booking': 'Confirmar Reserva',
    'login': 'Entrar',
    'start': 'Iniciar',
    'access_gaming_hub': 'Acesse seu centro de jogos',
    'email': 'E-mail',
    'password': 'Senha',
    'enter': 'Entrar',
    'continue_with': 'Ou continue com',
    'no_account': 'Não tem uma conta?',
    'create_account': 'Criar conta',
    'player_registration': 'Registro de Jogador',
    'new_game': 'Novo Jogo',
    'create_player_profile': 'Crie seu perfil de jogador para entrar no jogo',
    'player_name': 'Nome do Jogador',
    'confirm_password': 'Confirmar Senha',
    'contact_number': 'Número de Contato',
    'birth_date': 'Data de Nascimento',
    'select_class': 'Selecione a Classe',
    'warrior': 'Guerreiro',
    'mage': 'Mago',
    'rogue': 'Ladino',
    'mystery': 'Mistério',
    'id_number': 'Número de Identificação',
    'continue_quest': 'Continuar Missão',
    'already_have_account': 'Já tem uma conta?',
    'login_continue_journey': 'Faça login para continuar sua jornada',
    'base_location': 'Localização Base',
    'checkpoint': 'Ponto de Controle',
    'set_spawn_point': 'Defina as coordenadas do seu ponto de spawn',
    'street': 'Rua',
    'number': 'Número',
    'complement': 'Complemento',
    'district': 'Bairro',
    'city': 'Cidade',
    'state': 'Estado',
    'accept_terms': 'Eu aceito os termos de serviço e as regras do jogo',
    'complete_registration': 'Completar Registro',
    'link_account': 'Vincular Conta',
    'payment_methods': 'Métodos de Pagamento',
    'add_payment_method': 'Adicionar Método de Pagamento',
    'current_balance': 'Saldo Atual',
    'transaction_history': 'Histórico de Transações',
    'welcome_to_app': 'Bem-vindo à Central do Jogador',
    'onboarding_welcome_message': 'Vamos começar com nosso aplicativo!',
    'key_features': 'Recursos Principais',
    'feature_1': 'Reserve instalações esportivas facilmente',
    'feature_2': 'Gerencie suas reservas',
    'feature_3': 'Acompanhe seu progresso e conquistas',
    'how_to_book': 'Como Reservar',
    'booking_instructions': 'Navegue pelas instalações, selecione uma data e hora e confirme sua reserva.',
    'payment_instructions': 'Adicione seus métodos de pagamento preferidos para transações rápidas e fáceis.',
    'app_settings': 'Configurações do Aplicativo',
    'choose_theme': 'Escolha o Tema',
    'light': 'Claro',
    'dark': 'Escuro',
    'previous': 'Anterior',
    'next': 'Próximo',
    'finish': 'Finalizar',
    'upcoming': 'Próximos',
    'completed': 'Concluídos',
    'cancelled': 'Cancelados',
    'booking_details': 'Detalhes da Reserva',
    'minutes': 'minutos',
    'price': 'Preço',
    'status': 'Status',
    'card_holder': 'Titular do Cartão',
    'add_card': 'Adicionar Cartão',
    'your_payment_methods': 'Seus Métodos de Pagamento',
    'expires': 'Expira em',
    'upcoming_games': 'Próximos Jogos',
    'recent_activities': 'Atividades Recentes',
    'leaderboard': 'Classificação',
    'view_all': 'Ver Todos',
    'points': 'Pontos',
    'rank': 'Posição',
    'total_games': 'Total de Jogos',
    'win_rate': 'Taxa de Vitórias',
    'xp': 'XP',
    'xp_progress': 'Progresso de XP',
    'level_up': 'Subiu de nível!',
    'new_level': 'Você atingiu o nível {level}!',
    'xp_earned': 'Você ganhou {xp} XP!',
    'first_blood': 'Primeira Vez',
    'first_blood_desc': 'Faça sua primeira reserva',
    'regular_player': 'Jogador Regular',
    'regular_player_desc': 'Faça 10 reservas',
    'facility_explorer': 'Explorador de Instalações',
    'facility_explorer_desc': 'Visite 5 instalações diferentes',
    'social_butterfly': 'Borboleta Social',
    'social_butterfly_desc': 'Adicione 5 amigos',
    'influencer': 'Influenciador',
    'influencer_desc': 'Compartilhe sua primeira conquista nas redes sociais',
    'early_bird': 'Madrugador',
    'early_bird_desc': 'Faça uma reserva antes das 8h',
    'night_owl': 'Coruja da Noite',
    'night_owl_desc': 'Faça uma reserva depois das 22h',
    'streak_master': 'Mestre da Sequência',
    'streak_master_desc': 'Faça reservas por 7 dias consecutivos',
    'diverse_athlete': 'Atleta Diversificado',
    'diverse_athlete_desc': 'Experimente 3 tipos diferentes de esportes',
    'referral_king': 'Rei das Indicações',
    'referral_king_desc': 'Indique 3 amigos que façam reservas',
    'match_registration': 'Registro de Informações das Partidas',
    'match_list': 'Lista de Partidas',
    'add_match': 'Adicionar Partida',
    'edit_match': 'Editar Partida',
    'update_match': 'Atualizar Partida',
    'notes': 'Notas',
    'start_time': 'Hora de Início',
    'end_time': 'Hora de Término',
    'select_field': 'Selecionar Campo',
    'field': 'Campo',
    'add_comment': 'Adicionar Comentário',
    'enter_comment': 'Digite seu comentário aqui',
    'rate_facility': 'Avaliar Instalação',
    'submit_comment': 'Enviar Comentário',
    'comment_added': 'Comentário adicionado com sucesso',
    'game_shared': 'Jogo compartilhado com sucesso',
    'facility_details': 'Detalhes da Instalação',
    'facility_description': 'Descrição',
    'facility_description_text': 'Instalação esportiva moderna com equipamentos e comodidades profissionais.',
    'amenities': 'Comodidades',
    'parking': 'Estacionamento Disponível',
    'lockers': 'Armários',
    'showers': 'Chuveiros',
    'equipment_rental': 'Aluguel de Equipamentos',
    'share_your_experience': 'Compartilhe sua experiência com esta instalação...',
    'submit_review': 'Enviar Avaliação',
    'review_submitted': 'Avaliação Enviada',
    'thank_you_feedback': 'Obrigado pelo seu feedback!',
    'image': 'Imagem',
    'facility_image': 'Imagem da Instalação',
    'select_time': 'Selecionar Horário',
    'booking_success': 'Reserva Realizada com Sucesso',
    'booking_error': 'Erro na Reserva',
    'please_select_date': 'Por favor, selecione uma data',
    'please_select_time': 'Por favor, selecione horário de início e fim',
    'please_select_field': 'Por favor, selecione um campo',
    'facility_images': 'Imagens da Instalação',
    'slide': 'Slide',
    'previous_image': 'Imagem Anterior',
    'next_image': 'Próxima Imagem',
    'loading': 'Carregando...',
    'no_bookings': 'Nenhuma reserva encontrada',
    'no_bookings_desc': 'Você ainda não fez nenhuma reserva',
    'book_facility_now': 'Reserve uma instalação agora',
    'booking_confirmation': 'Confirmação de Reserva',
    'booking_summary': 'Resumo da Reserva',
    'selected_date': 'Data Selecionada',
    'selected_time': 'Horário Selecionado',
    'selected_field': 'Campo Selecionado',
    'total_price': 'Preço Total',
    'payment_method': 'Método de Pagamento',
    'confirm_and_pay': 'Confirmar e Pagar',
    'booking_rules': 'Regras de Reserva',
    'min_duration': 'Duração mínima: 1 hora',
    'max_duration': 'Duração máxima: 3 horas',
    'cancellation_policy': 'Cancelamento grátis até 24 horas antes',
    'facility_rules': 'Regras da Instalação',
    'proper_attire': 'Traje esportivo adequado obrigatório',
    'equipment': 'Equipamentos disponíveis para aluguel',
    'no_food': 'Não é permitido comida ou bebida',
    'arrive_early': 'Chegue 10 minutos antes',
    'mobile_menu': 'Menu Mobile',
    'close_menu': 'Fechar Menu',
    'view_profile': 'Ver Perfil',
    'edit_profile': 'Editar Perfil',
    'view_bookings': 'Ver Reservas',
    'my_bookings': 'Minhas Reservas',
    'active_bookings': 'Reservas Ativas',
    'past_bookings': 'Reservas Anteriores',
    'facility_location': 'Localização da Instalação',
    'get_directions': 'Como Chegar',
    'share_facility': 'Compartilhar Instalação',
    'report_issue': 'Reportar Problema',
    'save_favorite': 'Salvar nos Favoritos',
    'remove_favorite': 'Remover dos Favoritos',
    'facility_saved': 'Instalação salva nos favoritos',
    'facility_removed': 'Instalação removida dos favoritos',
    'available_times': 'Horários Disponíveis',
    'no_times_available': 'Não há horários disponíveis para a data selecionada',
    'try_another_date': 'Por favor, tente outra data',
    'peak_hours': 'Horários de Pico',
    'off_peak_hours': 'Horários Fora de Pico',
    'peak_hour_rates': 'Tarifas de Horário de Pico Aplicadas',
    'off_peak_rates': 'Tarifas Fora de Pico Aplicadas',
    'reviews': 'Avaliações',
    'facility_reviews': 'Avaliações da Instalação',
    'mock_review': 'Esta é uma ótima instalação! Aproveitei meu tempo aqui e definitivamente voltaria.',
    'write_review': 'Escrever uma Avaliação',
    'write_your_review': 'Escreva sua avaliação aqui...',
    'match_results': 'Resultados da Partida',
    'match_date': 'Data da Partida',
    'team': 'Time',
    'team_name': 'Nome do Time',
    'score': 'Placar',
    'submit_results': 'Enviar Resultados',
    'Personal': 'Pessoal',
    'Contact': 'Contato',
    'Security': 'Segurança',
    'full_name': 'Nome Completo',
    'phone_number': 'Número de Telefone',
    'id_document': 'Documento de Identidade',
    'end_session': 'Encerrar Sessão',
    'recent_achievements': 'Conquistas Recentes',
    'help_and_support': 'Ajuda e Suporte',
    'search_faqs': 'Pesquisar FAQs',
    'search_faqs_description': 'Encontre respostas para perguntas comuns',
    'search_placeholder': 'Digite sua pergunta aqui...',
    'frequently_asked_questions': 'Perguntas Frequentes',
    'contact_support': 'Contatar Suporte',
    'contact_support_description': 'Não encontrou o que procura? Envie-nos uma mensagem.',
    'your_name': 'Seu Nome',
    'your_email': 'Seu Email',
    'your_question': 'Sua Pergunta',
    'submit_question': 'Enviar Pergunta',
    'query_submitted': 'Pergunta Enviada',
    'query_submitted_description': 'Recebemos sua pergunta e responderemos em breve.',
    'faq_question_1': 'Como faço para reservar uma instalação?',
    'faq_answer_1': 'Para reservar uma instalação, navegue até a página inicial, selecione a instalação desejada, escolha um horário disponível e confirme sua reserva.',
    'faq_question_2': 'Posso cancelar minha reserva?',
    'faq_answer_2': 'Sim, você pode cancelar sua reserva até 24 horas antes do horário agendado sem nenhuma penalidade.',
    'faq_question_3': 'Como posso ver meu histórico de reservas?',
    'faq_answer_3': 'Você pode ver seu histórico de reservas indo ao seu perfil e clicando no botão "Histórico de Reservas".',
    'faq_question_4': 'Como atualizo as informações do meu perfil?',
    'faq_answer_4': 'Para atualizar as informações do seu perfil, vá para a página do seu perfil e clique no botão "Editar Perfil". Você pode então modificar seus detalhes nas respectivas abas.',
    'faq_question_5': 'Como ganho XP e subo de nível?',
    'faq_answer_5': 'Você ganha XP reservando instalações, completando jogos e alcançando várias metas no aplicativo. Conforme você acumula XP, você automaticamente sobe de nível e desbloqueia novos recursos e recompensas.',
    'match_info_registration': 'Registro de Informações das Partidas',
    'match_info_description': 'Acompanhe suas partidas e o desempenho da equipe.',
    'match_info_feature_1': 'Registre pontuações e estatísticas das partidas',
    'match_info_feature_2': 'Acompanhe o desempenho individual dos jogadores',
    'match_info_feature_3': 'Gere relatórios e análises das partidas',
    'facility_ratings': 'Avaliações de Instalações',
    'ratings_description': 'Avalie e revise as instalações que você visita.',
    'ratings_feature_1': 'Avalie instalações com base em vários critérios',
    'ratings_feature_2': 'Leia e escreva avaliações detalhadas',
    'ratings_feature_3': 'Ajude outros usuários a encontrar as melhores instalações',
    'more': 'Mais',
    'match_info': 'Info. da Partida',
    'ratings': 'Avaliações',
    'current_password': 'Senha Atual',
    'new_password': 'Nova Senha',
    'confirm_new_password': 'Confirmar Nova Senha',
  }
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

